Repository ashishpapanai/chessJS, pull requests merged in 2021-01, with the labels that each got.

#59 Improved GUI for Issue#3
  images/chess1.jpg
  index.html
  styles.css
Labels: medium, merge-ready, swoc2021

#67 Issue#64, #65, #66: Created Single Template for GUI, Added Chess Board Themes, Added Help page
  README.md
  __pycache__/app.cpython-37.pyc
  about.css
  about.html
  app.py
  index.html
  static/Background_Img.jpeg
  static/about.css
  static/images/assissPhotoo.jpeg
  static/images/bB.png
  static/images/bK.png
  static/images/bN.png
  static/images/bP.png
  static/images/bQ.png
  static/images/bR.png
  static/images/chess1.jpg
  static/images/chess2.jpg
  static/images/favicon.ico
  static/images/think1.png
  static/images/think2.png
  static/images/think3.png
  static/images/vauPhotoo.jpeg
  static/images/wB.png
  static/images/wK.png
  static/images/wN.png
  static/images/wP.png
  static/images/wQ.png
  static/images/wR.png
  static/js/board.js
  static/js/defs.js
  static/js/evaluate.js
  static/js/gui.js
  static/js/io.js
  static/js/main.js
  static/js/makemove.js
  static/js/modal.js
  static/js/movegen.js
  static/js/perft.js
  static/js/pvtable.js
  static/js/search.js
  static/styles.css
  templates/about.html
  templates/help.html
  templates/index.html
  templates/template.html
Labels: enhancement, hard, medium, merge-ready, swoc2021

#82 GUI enhancement of all pages + Rules page
  LawsOfChess.pdf
  about.css
  about.html
  images/chess1.jpg
  images/chess2.jpg
  images/chess3.jpg
  images/diagnol.JPG
  images/initial-position.JPG
  images/kingmovement1.JPG
  images/kingmovement2.JPG
  images/knightmovement.JPG
  images/pawnmovement.JPG
  images/pawnmovement2.JPG
  images/queenmovement.JPG
  images/rookmovement.JPG
  index.html
  js/main.js
  rules.css
  rules.html
  styles.css
Labels: enhancement, medium, merge-ready, swoc2021

#90 Remove outline from the buttons and add hover effects instead Fixes #79
  styles.css
Labels: easy, merge-ready, swoc2021

#91 Fixed small bug (alligned nav items properly according to home page in about and help page)
  about.css
  rules.css
  styles.css
Labels: easy, good first issue, merge-ready, swoc2021
